// Public facade (package export "./audit"): the engine plus the terminal/markdown presentation.
// Core command paths import cli/audit-engine.js instead, so piped and --json runs never load
// the presentation layer (cli/seam.spec.js).
import { auditFile, resolveAuditConfig, scanTree, scanDirectory, runAudit } from './audit-engine.js';
import { PILLARS, RULE_REGISTRY } from './audit/rules.js';
import { createPatternRegistry } from './audit/pattern-detector.js';
import {
  buildRemediationRoadmap,
  formatRoadmapSection,
  formatRoadmapMarkdown,
  buildSelfHealingRoadmapPrompt
} from './audit/roadmap.js';
import {
  calculateMolecularHealthScore,
  calculateQuantumHealthScore,
  calculatePillarBreakdown,
  calculateTokenBurnAnalytics,
  calculateHotspots,
  calculateAiSlopScore
} from './audit/metrics.js';
import {
  formatTerminalReport,
  generateMarkdownReport,
  groupViolationsBySeverity,
  groupViolationsByDirectory,
  groupViolationsByRule,
  formatDirectoryDistributionSection,
  formatDirectoryRollupMarkdown,
  renderGroupedViolationsMarkdown,
  resolveTopSectionColor,
  formatScorecardSection,
  formatAiSlopSection,
  formatCriticalSection,
  formatHighMediumSection,
  formatLowSection,
  formatPillarsSection,
  formatSinglePillarSection,
  formatHotspotsSection,
  formatContextAnalysisSection,
  formatFailuresSection,
  formatPassesSection,
  formatGradeFSection,
  formatGradeDSection,
  formatGradeCSection,
  formatGradeBSection,
  formatGradeASection,
  getChemicalXAsciiBanner,
  getAsciiGradeLines,
  formatAsciiGrade,
  getReportCardAsciiLines,
  REPORT_CARD_ASCII,
  formatPillarReactionBadgesTerminal,
  formatPillarReactionBadgesMarkdown,
  formatPillarShieldBadges,
  resolveBadgeColor,
  PILLAR_EMOJIS,
  PILLAR_SHORT_NAMES
} from './audit/reporter.js';
import {
  buildGradeFPrompt,
  buildGradeDPrompt,
  buildGradeCPrompt,
  buildGradeBPrompt,
  buildAiSlopPrompt,
  buildHotspotsPrompt,
  buildPillarPrompt,
  buildMasterPrompt,
  deduplicateRolePreambles,
  formatPromptBox,
  formatGroupedPromptViolations
} from './audit/prompts.js';

export { auditFile, resolveAuditConfig, scanTree, scanDirectory, runAudit };

export * from './audit/social.js';
export * from './audit/prompts.js';
export * from './audit/history.js';

export {
  calculateMolecularHealthScore,
  calculateQuantumHealthScore,
  calculateAiSlopScore,
  calculatePillarBreakdown,
  calculateTokenBurnAnalytics,
  calculateHotspots,
  PILLARS,
  RULE_REGISTRY,
  formatTerminalReport,
  generateMarkdownReport,
  groupViolationsBySeverity,
  groupViolationsByDirectory,
  groupViolationsByRule,
  formatDirectoryDistributionSection,
  formatDirectoryRollupMarkdown,
  renderGroupedViolationsMarkdown,
  resolveTopSectionColor,
  formatScorecardSection,
  formatAiSlopSection,
  formatCriticalSection,
  formatHighMediumSection,
  formatLowSection,
  formatPillarsSection,
  formatSinglePillarSection,
  formatHotspotsSection,
  formatContextAnalysisSection,
  formatFailuresSection,
  formatPassesSection,
  formatGradeFSection,
  formatGradeDSection,
  formatGradeCSection,
  formatGradeBSection,
  formatGradeASection,
  getChemicalXAsciiBanner,
  getAsciiGradeLines,
  formatAsciiGrade,
  getReportCardAsciiLines,
  REPORT_CARD_ASCII,
  formatPillarReactionBadgesTerminal,
  formatPillarReactionBadgesMarkdown,
  formatPillarShieldBadges,
  resolveBadgeColor,
  PILLAR_EMOJIS,
  PILLAR_SHORT_NAMES,
  buildGradeFPrompt,
  buildGradeDPrompt,
  buildGradeCPrompt,
  buildGradeBPrompt,
  buildAiSlopPrompt,
  buildHotspotsPrompt,
  buildPillarPrompt,
  buildMasterPrompt,
  deduplicateRolePreambles,
  formatPromptBox,
  formatGroupedPromptViolations,
  createPatternRegistry,
  buildRemediationRoadmap,
  formatRoadmapSection,
  formatRoadmapMarkdown,
  buildSelfHealingRoadmapPrompt
};

export * from './audit/rules-predicates.js';

export default {
  auditFile,
  scanDirectory,
  runAudit,
  formatTerminalReport,
  generateMarkdownReport,
  groupViolationsBySeverity,
  groupViolationsByDirectory,
  groupViolationsByRule,
  formatDirectoryDistributionSection,
  formatDirectoryRollupMarkdown,
  renderGroupedViolationsMarkdown,
  resolveTopSectionColor,
  formatScorecardSection,
  formatAiSlopSection,
  formatCriticalSection,
  formatHighMediumSection,
  formatLowSection,
  formatPillarsSection,
  formatHotspotsSection,
  formatContextAnalysisSection,
  formatFailuresSection,
  formatPassesSection,
  formatGradeFSection,
  formatGradeDSection,
  formatGradeCSection,
  formatGradeBSection,
  formatGradeASection,
  getChemicalXAsciiBanner,
  getAsciiGradeLines,
  formatAsciiGrade,
  getReportCardAsciiLines,
  REPORT_CARD_ASCII,
  formatPillarReactionBadgesTerminal,
  formatPillarReactionBadgesMarkdown,
  formatPillarShieldBadges,
  resolveBadgeColor,
  PILLAR_SHORT_NAMES,
  PILLARS,
  RULE_REGISTRY,
  buildGradeFPrompt,
  buildGradeDPrompt,
  buildGradeCPrompt,
  buildGradeBPrompt,
  buildAiSlopPrompt,
  buildHotspotsPrompt,
  buildPillarPrompt,
  buildMasterPrompt,
  deduplicateRolePreambles,
  formatPromptBox,
  formatGroupedPromptViolations,
  createPatternRegistry,
  buildRemediationRoadmap,
  formatRoadmapSection,
  formatRoadmapMarkdown,
  buildSelfHealingRoadmapPrompt
};
