import { renderBanner } from './terminal.js';

export const printHelp = () => {
  renderBanner('Chemical X Protocol: CLI Usage & Reference');

  const BOLD = '\x1b[1m';
  const CYAN = '\x1b[36m';
  const DIM = '\x1b[2m';
  const YELLOW = '\x1b[33m';
  const GREEN = '\x1b[32m';
  const RESET = '\x1b[0m';

  const out = [
    `${BOLD}USAGE${RESET}`,
    `  ${CYAN}npx chemx${RESET} <command> [options]`,
    `  ${CYAN}npm create chemx${RESET} [directory]`,
    '',
    `${BOLD}COMMANDS${RESET}`,
    `  ${CYAN}build${RESET} [options] [-- <command>]  ${DIM}(aliases: run, wrap)${RESET}`,
    `      Wrap and audit arbitrary build scripts with token-conserving silent execution.`,
    `      Suppresses multi-thousand-line compiler noise, catalogs diagnostics into`,
    `      grouped categories (TypeScript, Vite/Rollup, Style, Budget), and provides`,
    `      actionable remediation hints and machine-readable JSON for AI agents.`,
    `      Flags: ${CYAN}--json${RESET}, ${CYAN}--silent${RESET}, ${CYAN}--raw${RESET}, ${CYAN}--summary${RESET}`,
    `      Examples: ${CYAN}npx chemx build${RESET} or ${CYAN}npx chemx build -- pnpm build${RESET}`,
    '',
    `  ${CYAN}audit${RESET} [options]`,
    `      Run the 7-Pillar Molecular Architecture static analysis audit.`,
    `      Scans AST for line budgets, control flow booleans, nested ternaries,`,
    `      hook limits, self-cleaning timers, and Anti-Tailwind-Soup compliance.`,
    `      Computes Molecular Health Index (MHI: 0-100) and letter grades (A+ to F).`,
    `      Defaults to interactive zero-scroll Gum terminal dashboard.`,
    '',
    `  ${CYAN}generate${RESET} [name]  ${DIM}(aliases: capsule, add)${RESET}`,
    `      Launch the interactive Molecular Capsule Generator wizard.`,
    `      Scaffolds a compliant, crystalline capsule directory with:`,
    `        ${DIM}- ${RESET}<name>.<ext>           ${DIM}(React .tsx, Vue .vue, or Svelte .svelte < 100 lines)${RESET}`,
    `        ${DIM}- ${RESET}<name>.controller.ts   ${DIM}(pure reactive state & 2-stage booleans)${RESET}`,
    `        ${DIM}- ${RESET}_<name>.scss          ${DIM}(mixin-only glass styling with zero inline styles)${RESET}`,
    `        ${DIM}- ${RESET}types.d.ts             ${DIM}(discriminated union states and props interfaces)${RESET}`,
    `        ${DIM}- ${RESET}index.ts               ${DIM}(clean public barrel export)${RESET}`,
    `      Flags: ${CYAN}--tier=m|a|o|t${RESET}, ${CYAN}--framework=react|vue|svelte${RESET}, ${CYAN}--dir=<path>${RESET}, ${CYAN}-y${RESET}`,
    `      Example: ${CYAN}npx chemx generate${RESET} or ${CYAN}npx chemx generate m-user-avatar -y${RESET}`,
    '',
    `  ${CYAN}init${RESET} [directory]`,
    `      ${YELLOW}[PAID]${RESET} Drop full Chemical X blueprints, core hooks (toResult,`,
    `      useAsyncData, useSelfCleaningTimer), and AGENTS.md directives into`,
    `      an existing codebase. Default destination: ${CYAN}src/chemical-x${RESET}.`,
    `      Requires Single Dev ($27) or Team Power Puff ($97: Unlimited Lifetime) license.`,
    '',
    `  ${CYAN}create${RESET} [directory]  ${DIM}(or: npm create chemx [directory])${RESET}`,
    `      ${YELLOW}[PAID]${RESET} Scaffold a complete, clean-slate project wired with full`,
    `      Chemical X molecular standards, pre-commit line budget hooks, and rules.`,
    `      Requires Single Dev ($27) or Team Power Puff ($97: Unlimited Lifetime) license.`,
    '',
    `  ${CYAN}install-hooks${RESET} [directory]  ${DIM}(aliases: hook, setup-ci)${RESET}`,
    `      ${GREEN}[FREE]${RESET} Install git pre-commit hook (.git/hooks/pre-commit) and`,
    `      GitHub Actions CI workflow (.github/workflows/chemx-audit.yml).`,
    `      Enforces 500-line file ceilings, 100-line molecule budgets, and configurable`,
    `      minimum grade/score thresholds with automatic AI prompt clipboard copying.`,
    `      Example: ${CYAN}npx chemx install-hooks${RESET}`,
    '',
    `  ${CYAN}badge${RESET} [options]  ${DIM}(aliases: badges)${RESET}`,
    `      ${GREEN}[FREE]${RESET} Generate and copy verified Chemical X footer badges for your site.`,
    `      Outputs Vue 3 SFC, React 19 TSX, Svelte 5, HTML/CSS, Markdown, or SVG.`,
    `      Automatically reads latest audit grade from .chemx/history.json or baseline.`,
    `      Flags: ${CYAN}--format=vue|react|html|markdown|svg|all${RESET}, ${CYAN}--grade=A+${RESET}, ${CYAN}--label="..."${RESET}, ${CYAN}--copy${RESET}`,
    `      Example: ${CYAN}npx chemx badge${RESET} or ${CYAN}npx chemx badge --format=html --copy${RESET}`,
    '',
    `  ${CYAN}mcp${RESET}  ${DIM}(aliases: mcp-server)${RESET}`,
    `      ${GREEN}[FREE]${RESET} Launch the Chemical X Model Context Protocol (MCP) server.`,
    `      Communicates via JSON-RPC 2.0 stdio with Cursor, Claude Desktop, Windsurf, and Antigravity.`,
    `      Exposes 6 core tools (chemx_query_patterns, chemx_autofix, chemx_audit,`,
    `      chemx_generate_capsule, chemx_get_refactor_prompt, chemx_audit_build),`,
    `      living resources (chemx://directives, chemx://scorecard), and prompts.`,
    `      Example: ${CYAN}npx chemx mcp${RESET}`,
    '',
    `  ${CYAN}install-mcp${RESET} [directory]  ${DIM}(aliases: setup-mcp)${RESET}`,
    `      ${GREEN}[FREE]${RESET} Auto-configure Chemical X MCP server for your project and tools.`,
    `      Registers in .cursor/mcp.json, .vscode/mcp.json, and ~/.gemini/config/mcp_config.json.`,
    `      Example: ${CYAN}npx chemx install-mcp${RESET}`,
    '',
    `  ${CYAN}help${RESET}, ${CYAN}--help${RESET}, ${CYAN}-h${RESET}`,
    `      Display this comprehensive CLI documentation and options guide.`,
    '',
    `${BOLD}AUDIT OPTIONS & FLAGS${RESET}`,
    `  ${CYAN}--dir=<path>${RESET}`,
    `      Directory to analyze. Defaults to ${CYAN}src${RESET} if present, else current working directory.`,
    `      Example: ${CYAN}npx chemx audit --dir=apps/web/src${RESET}`,
    '',
    `  ${CYAN}--json${RESET}`,
    `      Output structured machine-readable JSON report to stdout.`,
    `      Ideal for CI/CD pipelines, automated gating, and custom tooling.`,
    '',
    `  ${CYAN}--markdown${RESET}, ${CYAN}--md${RESET}`,
    `      Output formatted GitHub Flavored Markdown report to stdout.`,
    '',
    `  ${CYAN}--output=<file>${RESET}, ${CYAN}-o=<file>${RESET}`,
    `      Save formatted Markdown report directly to the specified file path.`,
    `      Example: ${CYAN}npx chemx audit --output=AUDIT_REPORT.md${RESET}`,
    '',
    `  ${CYAN}--unroll${RESET}, ${CYAN}--all${RESET}`,
    `      Stream full unrolled report directly to terminal without interactive Gum menu.`,
    '',
    `  ${CYAN}--share${RESET}, ${CYAN}--post${RESET}`,
    `      Publish or update report on GitHub Discussions without entering dashboard.`,
    `      Automatically archives prior audit snapshots as discussion comments.`,
    '',
    `  ${CYAN}--strict${RESET}`,
    `      Strict CI failure mode: exits with status 1 on ANY violation, including`,
    `      Low hygiene issues (typography and console logging).`,
    '',
    `  ${CYAN}--min-grade=<tier>${RESET}`,
    `      Fail audit if Molecular Health Index grade falls below tier (A+, A, B, C, D).`,
    `      Default: None (or B when executed via pre-commit gatekeeper).`,
    '',
    `  ${CYAN}--min-score=<0-100>${RESET}`,
    `      Fail audit if Molecular Health Index score falls below number (e.g. 80).`,
    '',
    `  ${CYAN}--model=<claude|gpt4o|blended>${RESET}`,
    `      Pricing baseline for context burn dollar calculations ($3.00/1M blended).`,
    '',
    `  ${CYAN}--prompt-on-fail${RESET}, ${CYAN}--copy-prompt${RESET}`,
    `      Automatically copy the synthesized AI refactoring prompt to system clipboard`,
    `      when architectural violations or threshold failures are detected.`,
    '',
    `  ${CYAN}--license=<key>${RESET}`,
    `      Pass Chemical X Sponsor or Team license key non-interactively via CLI.`,
    `      Tiers: Single Dev ($27) | Team Power Puff ($97: Unlimited Lifetime).`,
    '',
    `${BOLD}ENVIRONMENT VARIABLES${RESET}`,
    `  ${GREEN}CHEMX_MIN_GRADE${RESET}`,
    `      Default minimum grade threshold for pre-commit gatekeeper (default: B).`,
    '',
    `  ${GREEN}CHEMX_MIN_SCORE${RESET}`,
    `      Default minimum score threshold for pre-commit gatekeeper (default: 80).`,
    '',
    `  ${GREEN}GH_TOKEN${RESET} / ${GREEN}GITHUB_TOKEN${RESET}`,
    `      GitHub personal access token for automated discussion publishing via GraphQL.`,
    `      If omitted, the CLI automatically delegates to local ${CYAN}gh${RESET} CLI authentication.`,
    '',
    `  ${GREEN}CHEMICAL_X_API_URL${RESET}`,
    `      Custom licensing edge verification endpoint. Default: ${CYAN}https://chemicalx.xophz.com${RESET}.`,
    '',
    `${BOLD}EXAMPLES${RESET}`,
    `  ${DIM}# Run interactive audit dashboard with ASCII banner and health scorecard:${RESET}`,
    `  ${CYAN}npx chemx audit${RESET}`,
    '',
    `  ${DIM}# Scan a sub-package in strict mode for CI gating:${RESET}`,
    `  ${CYAN}npx chemx audit --dir=packages/core --strict${RESET}`,
    '',
    `  ${DIM}# Export markdown scorecard to file:${RESET}`,
    `  ${CYAN}npx chemx audit --markdown --output=AUDIT.md${RESET}`,
    '',
    `  ${DIM}# Pipe JSON metrics to jq:${RESET}`,
    `  ${CYAN}npx chemx audit --json | jq .health${RESET}`,
    '',
    `  ${DIM}# Generate a new molecule capsule:${RESET}`,
    `  ${CYAN}npx chemx generate m-spark-kpi${RESET}`,
    '',
    `  ${DIM}# Scaffold a new project:${RESET}`,
    `  ${CYAN}npm create chemx my-awesome-app${RESET}`,
    '',
    `  ${DIM}# Run token-conserving silent build audit with structured diagnostics:${RESET}`,
    `  ${CYAN}npx chemx build --silent${RESET}`,
    '',
    `  ${DIM}# Wrap arbitrary build command and output AI-ready JSON:${RESET}`,
    `  ${CYAN}npx chemx build --json -- pnpm run build${RESET}`,
    ''
  ].join('\n');

  process.stdout.write(out + '\n');
};
