import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PILLAR_PRESETS } from './pillars-schema.js';
import { buildHostShims, HOST_SHIM_FILES, SHIM_TOKEN_BUDGET } from './host-shims.js';
import { isGeneratedContent } from './pillars-write-guard.js';
import { buildMcpInstructions } from './mcp/antigravity.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const estimateTokens = (text) => Math.ceil(text.length / 4);

const THRESHOLD_PATTERNS = [
  /\b\d+\s*-?\s*(?:lines?|LOC|props?|hooks?|levels?|decision points?)\b/gi,
  /\b(?:max(?:imum)?|under|at most|outer bound of|soft warning at)\s+\d+/gi,
  /[<>]=?\s*\d+/g
];
const findThresholds = (text) => THRESHOLD_PATTERNS.flatMap((pattern) => text.match(pattern) || []);

const strictShims = buildHostShims(PILLAR_PRESETS.strict.pillars, { projectName: 'demo-app' });

test('host-shims: builds one shim per host file', () => {
  assert.deepStrictEqual(Object.keys(strictShims).sort(), [...HOST_SHIM_FILES].sort());
});

for (const file of HOST_SHIM_FILES) {
  test(`host-shims: ${file} points at AGENTS.md, carries the marker, and fits the budget`, () => {
    const text = strictShims[file];
    assert.ok(text.includes('AGENTS.md'), `${file} must name the canonical rulebook`);
    assert.ok(isGeneratedContent(text), `${file} must carry the generated marker`);
    assert.ok(estimateTokens(text) < SHIM_TOKEN_BUDGET, `${file} is ${estimateTokens(text)} tokens`);
    assert.strictEqual(text.includes('—'), false, `${file} must not contain em dashes`);
  });

  test(`host-shims: ${file} states no threshold (AGENTS.md owns them)`, () => {
    assert.deepStrictEqual(findThresholds(strictShims[file]), []);
  });

  test(`host-shims: committed ${file} is a generated shim that states no threshold`, () => {
    const text = fs.readFileSync(path.join(repoRoot, file), 'utf8');
    assert.ok(isGeneratedContent(text), `${file} must be regenerated by chemx pillars, not hand-edited`);
    assert.ok(estimateTokens(text) < SHIM_TOKEN_BUDGET, `${file} is ${estimateTokens(text)} tokens`);
    assert.deepStrictEqual(findThresholds(text), []);
  });
}

test('host-shims: CLAUDE.md names projectRoot for mutating MCP calls and scopes enrich', () => {
  const text = strictShims['CLAUDE.md'];
  assert.ok(text.includes('projectRoot'));
  assert.match(text, /enrich[^\n]*component/i);
});

test('host-shims: Antigravity MCP instructions point at AGENTS.md and state no threshold', () => {
  const text = buildMcpInstructions();
  assert.ok(text.includes('AGENTS.md'));
  assert.ok(text.includes('projectRoot'));
  assert.deepStrictEqual(findThresholds(text), []);
});

test('host-shims: committed Copilot instructions point at AGENTS.md and state no threshold', () => {
  const text = fs.readFileSync(path.join(repoRoot, '.github/copilot-instructions.md'), 'utf8');
  assert.ok(text.includes('AGENTS.md'));
  assert.ok(estimateTokens(text) < SHIM_TOKEN_BUDGET, `copilot-instructions.md is ${estimateTokens(text)} tokens`);
  assert.deepStrictEqual(findThresholds(text), []);
});

test('host-shims: lists only the selected pillars', () => {
  const shims = buildHostShims(['p1_line_budgets'], { projectName: 'demo-app' });
  for (const file of HOST_SHIM_FILES) {
    assert.ok(shims[file].includes('Molecular Line Budgets'), file);
    assert.strictEqual(shims[file].includes('Swarm Task Backlog'), false, file);
  }
});

test('host-shims: the threshold detector catches the contradictions it guards against', () => {
  assert.ok(findThresholds('100-line outer bound per molecule capsule file.').length > 0);
  assert.ok(findThresholds('Strict File Line Outer Bound (< 100 lines)').length > 0);
  assert.ok(findThresholds('Max 12 decision points per hook').length > 0);
  assert.deepStrictEqual(findThresholds('Active pillars: Molecular Line Budgets, Table-of-Contents Views'), []);
});
