/**
 * Chemical X Protocol: Interactive Pillars Selection Wizard
 * Conscious opt-in for architectural standards and agent steering configuration.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { hasGum, gumChoose, promptQuestion, isStdinTty } from './terminal.js';
import { renderTtyBanner } from './tty-banner.js';
import { PILLARS, PILLAR_PRESETS } from './pillars-schema.js';
import { planFileWrite, applyFileWrites } from './pillars-write-guard.js';
import { buildHostShims } from './host-shims.js';
import { hasPreviewFlag } from './cli-args.js';
import { readExistingProjectConfig } from './config/loader.js';

const AGENTS_TEMPLATE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'AGENTS.md');

// AGENTS.md is hand-authored and canonical: seeded from the template when absent, never modified.
const agentsSeedTarget = (cwd) => {
  const file = path.resolve(cwd, 'AGENTS.md');
  const needsSeed = !fs.existsSync(file) && fs.existsSync(AGENTS_TEMPLATE);
  return needsSeed ? [{ file, content: fs.readFileSync(AGENTS_TEMPLATE, 'utf-8'), isGuarded: true }] : [];
};

const HAND_AUTHORED_REASON = 'not generated by chemx. Pass --force to overwrite (a backup is written first).';
const UNPARSABLE_CONFIG_REASON = 'it does not parse as a JSON object, so its settings would be lost. Nothing was written; fix it and re-run.';

export const runPillarsWizard = async (rawArgs = [], cwd = process.cwd()) => {
  const isJson = rawArgs.includes('--json');
  const isYes = rawArgs.includes('-y') || rawArgs.includes('--yes') || !isStdinTty();
  const isWrite = rawArgs.includes('--write');
  const isForce = rawArgs.includes('--force');
  const isDryRun = !isWrite || hasPreviewFlag(rawArgs);

  if (!isJson) {
    await renderTtyBanner('Chemical X: Architectural Pillars Wizard');
  }

  const presetFlag = (rawArgs.find((a) => a.startsWith('--preset=')) || '').split('=')[1];
  let selectedPresetKey = presetFlag ? presetFlag.toLowerCase() : null;
  let selectedPillarIds = [];

  const useGum = hasGum();

  const isKnownPreset = Boolean(selectedPresetKey && PILLAR_PRESETS[selectedPresetKey]);
  if (isKnownPreset) {
    selectedPillarIds = [...PILLAR_PRESETS[selectedPresetKey].pillars];
  } else if (isYes) {
    selectedPresetKey = 'recommended';
    selectedPillarIds = [...PILLAR_PRESETS.recommended.pillars];
  } else {
    const choices = [
      '1. Recommended / Balanced (Line budgets, Tiers, TOC views, Composables, AST query)',
      '2. Strict Chemical X (All 7 Pillars + Verification-First)',
      '3. Custom Pillar Selection (Review & toggle each pillar)',
      '4. Minimal (Line budgets only, no agent steering)',
      '5. None (Skip - do not install AGENTS.md or host shims)'
    ];

    const pick = useGum
      ? gumChoose(choices, 'Select Architectural Pillars Configuration')
      : await promptQuestion('Select Pillars: [1=Recommended, 2=Strict, 3=Custom, 4=Minimal, 5=None] (default: 1): ');

    if (pick && (pick.startsWith('2.') || pick === '2')) {
      selectedPresetKey = 'strict';
      selectedPillarIds = [...PILLAR_PRESETS.strict.pillars];
    } else if (pick && (pick.startsWith('3.') || pick === '3')) {
      selectedPresetKey = 'custom';
      for (const pillar of PILLARS) {
        const defaultChoice = PILLAR_PRESETS.recommended.pillars.includes(pillar.id) ? 'Y/n' : 'y/N';
        const isDefaultYes = defaultChoice === 'Y/n';
        const answer = await promptQuestion(`Enable ${pillar.title}? (${defaultChoice}): `);
        const isYesAnswer = answer ? answer.trim().toLowerCase().startsWith('y') : isDefaultYes;
        if (isYesAnswer) {
          selectedPillarIds.push(pillar.id);
        }
      }
    } else if (pick && (pick.startsWith('4.') || pick === '4')) {
      selectedPresetKey = 'minimal';
      selectedPillarIds = [...PILLAR_PRESETS.minimal.pillars];
    } else if (pick && (pick.startsWith('5.') || pick === '5')) {
      selectedPresetKey = 'none';
      selectedPillarIds = [];
    } else {
      selectedPresetKey = 'recommended';
      selectedPillarIds = [...PILLAR_PRESETS.recommended.pillars];
    }
  }

  // Build config object
  const pillarsConfig = {};
  for (const pillar of PILLARS) {
    pillarsConfig[pillar.key] = selectedPillarIds.includes(pillar.id);
  }

  // Read like the installer does, so comments are stripped and a broken file is never replaced.
  const configFile = path.resolve(cwd, '.chemx', 'config.json');
  const existingConfig = readExistingProjectConfig(cwd);
  const isConfigUnparsable = existingConfig === null;

  const updatedConfig = {
    ...existingConfig,
    pillars: pillarsConfig
  };

  const targets = [
    { file: configFile, content: JSON.stringify(updatedConfig, null, 2) + '\n', isGuarded: false, isLocked: isConfigUnparsable }
  ];

  const hasSelectedPillars = selectedPillarIds.length > 0;
  if (hasSelectedPillars) {
    const projectName = path.basename(path.resolve(cwd));
    const shims = Object.entries(buildHostShims(selectedPillarIds, { projectName }));
    targets.push(
      ...agentsSeedTarget(cwd),
      ...shims.map(([rel, content]) => ({ file: path.resolve(cwd, rel), content, isGuarded: true }))
    );
  }

  const toRelative = (file) => path.relative(cwd, file);
  // A locked target is refused even with --force: merging into it would drop settings it cannot read.
  const planTarget = (t) => (t.isLocked ? { file: t.file, action: 'refused', backupPath: null } : planFileWrite(t.file, t.content, { isForce, isGuarded: t.isGuarded }));
  const plans = targets.map((t) => ({ ...planTarget(t), content: t.content }));
  const unparsableConfig = isConfigUnparsable ? toRelative(configFile) : null;
  const refused = plans.filter((p) => p.action === 'refused').map((p) => toRelative(p.file));
  const hasRefusals = refused.length > 0;
  const shouldApply = !isDryRun && !hasRefusals;

  if (shouldApply) {
    fs.mkdirSync(path.dirname(configFile), { recursive: true });
  }
  const filesWritten = shouldApply ? applyFileWrites(plans).map(toRelative) : [];
  const planned = plans.map(({ file, action, backupPath }) => ({ file: toRelative(file), action, backupPath: backupPath && toRelative(backupPath) }));

  const result = {
    success: !hasRefusals,
    dryRun: isDryRun,
    preset: selectedPresetKey,
    selectedPillarIds,
    filesWritten,
    planned,
    refused,
    unparsableConfig,
    pillarsConfig
  };

  if (isJson) {
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
    return result;
  }

  const heading = isDryRun ? '\x1b[1m\x1b[33m[PREVIEW]\x1b[0m Planned' : '\x1b[1m\x1b[32m✔\x1b[0m Applied';
  process.stdout.write(`\n${heading} architectural pillars configuration (${selectedPresetKey}):\n`);
  for (const p of PILLARS) {
    const isEnabled = selectedPillarIds.includes(p.id);
    const icon = isEnabled ? '\x1b[32m✔\x1b[0m' : '\x1b[2m○\x1b[0m';
    process.stdout.write(`  ${icon} ${p.title}\n`);
  }
  process.stdout.write('\nFiles:\n');
  for (const plan of planned) {
    const backupNote = plan.backupPath ? ` (backup: ${plan.backupPath})` : '';
    process.stdout.write(`  ${plan.action.padEnd(9)} ${plan.file}${backupNote}\n`);
  }
  for (const file of refused) {
    const reason = file === unparsableConfig ? UNPARSABLE_CONFIG_REASON : HAND_AUTHORED_REASON;
    process.stdout.write(`\n\x1b[31mRefusing to overwrite ${file}: ${reason}\x1b[0m\n`);
  }
  if (isDryRun) {
    process.stdout.write('\nNo changes were written to disk. Run with --write to apply.\n\n');
  } else {
    process.stdout.write('\n');
  }

  return result;
};
